/**
 * Configurable Legal Metrology Rules Registry
 * Primary source of truth: The Legal Metrology (Packaged Commodities) Rules, 2011
 */

const statutoryRules = [
  {
    id: 'rule-lmr-06-1-a',
    ruleCode: 'LMR-06-1-A',
    ruleReference: 'Rule 6(1)(a) read with Rule 10',
    title: 'Manufacturer / Packer / Importer Name & Address',
    category: 'Entity Identification',
    requirement: 'Every package shall bear the name and complete address of the manufacturer, or where manufacturer is not the packer, name and address of manufacturer and packer; and for any imported package the name and address of importer.',
    statutoryExplanation: 'Rule 10 requires postal address with street, factory, city, state, or Postal Index Number (PIN) code so that a consumer can identify and locate the entity.',
    validationType: 'required_field',
    severity: 'CRITICAL',
    automationStatus: 'AUTOMATED',
    actSectionPenalty: 'Section 36(1) of Legal Metrology Act, 2009 (Fine up to ₹25,000 for first offence, up to ₹50,000 for second offence)',
    isActive: true,
  },
  {
    id: 'rule-lmr-06-1-b',
    ruleCode: 'LMR-06-1-B',
    ruleReference: 'Rule 6(1)(b)',
    title: 'Generic / Common Name of Commodity',
    category: 'Commodity Identity',
    requirement: 'The common or generic names of the commodity contained in the package and in case of packages with more than one product, the name and number or quantity of each product shall be mentioned.',
    statutoryExplanation: 'Prevents deceptive or confusing brand names from concealing the true identity of the product.',
    validationType: 'presence',
    severity: 'MAJOR',
    automationStatus: 'AUTOMATED',
    actSectionPenalty: 'Section 36(1) of Legal Metrology Act, 2009',
    isActive: true,
  },
  {
    id: 'rule-lmr-06-1-c',
    ruleCode: 'LMR-06-1-C',
    ruleReference: 'Rule 6(1)(c) read with Rule 11, 12, 13',
    title: 'Net Quantity in Standard Metric Units',
    category: 'Net Quantity & Units',
    requirement: 'The net quantity, in terms of the standard unit of weight or measure, of the commodity contained in the package or where the commodity is packed or sold by number, the number of the commodity contained in the package shall be mentioned.',
    statutoryExplanation: 'Must use metric units (g, kg for mass; ml, l for liquid volume; cm, m for length). Weight of packaging wrappers must be excluded.',
    validationType: 'numeric_value',
    severity: 'CRITICAL',
    automationStatus: 'AUTOMATED',
    actSectionPenalty: 'Section 36(1) & Section 36(2) of Legal Metrology Act, 2009',
    isActive: true,
  },
  {
    id: 'rule-lmr-12-6',
    ruleCode: 'LMR-12-6',
    ruleReference: 'Rule 12(6)',
    title: 'Prohibition on Misleading Quantity Qualifiers',
    category: 'Net Quantity & Units',
    requirement: 'The declaration of quantity shall not contain any word or expression which tends to create or likely to create an exaggerated, misleading or inadequate impression as to the quantity, for example: "minimum", "not less than", "average", "about", "approx", or "when packed".',
    statutoryExplanation: 'Prohibits packers from dodging exact weight compliance by claiming moisture loss or approximate weights.',
    validationType: 'text_format',
    severity: 'CRITICAL',
    automationStatus: 'AUTOMATED',
    actSectionPenalty: 'Section 36(1) of Legal Metrology Act, 2009',
    isActive: true,
  },
  {
    id: 'rule-lmr-06-1-d',
    ruleCode: 'LMR-06-1-D',
    ruleReference: 'Rule 6(1)(d)',
    title: 'Month and Year of Manufacture / Packing / Import',
    category: 'Traceability & Dates',
    requirement: 'The month and year in which the commodity is manufactured or pre-packed or imported shall be mentioned on the package.',
    statutoryExplanation: 'May be expressed either in words, or by numerals indicating the month and year, or by both (e.g., 08/2026, Aug 2026). Provisos exempt bidis, incense sticks, and LPG cylinders.',
    validationType: 'date_format',
    severity: 'MAJOR',
    automationStatus: 'AUTOMATED',
    actSectionPenalty: 'Section 36(1) of Legal Metrology Act, 2009',
    isActive: true,
  },
  {
    id: 'rule-lmr-06-1-e',
    ruleCode: 'LMR-06-1-E',
    ruleReference: 'Rule 6(1)(e) read with Rule 2(m)',
    title: 'Retail Sale Price (MRP) with Mandatory Tax Inclusivity',
    category: 'Pricing & Taxation',
    requirement: 'The retail sale price shall be printed on the package in the manner: "Maximum or Max. retail price Rs. ... inclusive of all taxes" or "MRP Rs. ... incl., of all taxes".',
    statutoryExplanation: 'Rule 2(m) strictly mandates that the retail sale price must state that all taxes are included to protect consumers from surcharge exploitation.',
    validationType: 'text_format',
    severity: 'CRITICAL',
    automationStatus: 'AUTOMATED',
    actSectionPenalty: 'Section 36(1) of Legal Metrology Act, 2009',
    isActive: true,
  },
  {
    id: 'rule-lmr-06-2',
    ruleCode: 'LMR-06-2',
    ruleReference: 'Rule 6(2)',
    title: 'Consumer Grievance Redressal / Care Details',
    category: 'Consumer Protection',
    requirement: 'Every package shall bear the name, address, telephone number, and e-mail address, if available, of the person who can be or the office which can be, contacted, in case of consumer complaints.',
    statutoryExplanation: 'Enables consumers to contact the manufacturer or packer directly regarding defective or deficient commodities.',
    validationType: 'required_field',
    severity: 'CRITICAL',
    automationStatus: 'AUTOMATED',
    actSectionPenalty: 'Section 36(1) of Legal Metrology Act, 2009',
    isActive: true,
  },
  {
    id: 'rule-lmr-06-3',
    ruleCode: 'LMR-06-3',
    ruleReference: 'Rule 6(3)',
    title: 'Prohibition on Alteration Stickers',
    category: 'Packaging Integrity',
    requirement: 'It shall not be permissible to affix individual stickers on the package for altering or making declaration required under these rules: Provided that for reducing the MRP, a sticker with revised lower MRP may be affixed without covering original MRP.',
    statutoryExplanation: 'Prevents tampering or concealing statutory manufacturing dates or prices with overlay stickers.',
    validationType: 'presence',
    severity: 'CRITICAL',
    automationStatus: 'AUTOMATED_AND_MANUAL',
    actSectionPenalty: 'Section 36(1) of Legal Metrology Act, 2009',
    isActive: true,
  },
  {
    id: 'rule-lmr-07-font',
    ruleCode: 'LMR-07-FONT',
    ruleReference: 'Rule 7 (Table I & Table II)',
    title: 'Principal Display Panel Numeral & Letter Height',
    category: 'Display & Legibility',
    requirement: 'The height of any numeral in declaration on Principal Display Panel shall not be less than: 1mm for <=200g/ml, 2mm for 200g-500g, 4mm for >500g. Letter height shall not be less than 1mm (2mm when embossed/blown).',
    statutoryExplanation: 'Ensures legible visibility for consumers. Standard 2D photographs cannot guarantee calibrated physical mm dimensions without a certified gauge; therefore flagged for manual verification.',
    validationType: 'manual_verification',
    severity: 'MAJOR',
    automationStatus: 'MANUAL_VERIFICATION_REQUIRED',
    actSectionPenalty: 'Section 36(1) of Legal Metrology Act, 2009',
    isActive: true,
  },
  {
    id: 'rule-lmr-09-4',
    ruleCode: 'LMR-09-4',
    ruleReference: 'Rule 9(4)',
    title: 'Language of Declarations',
    category: 'Display & Legibility',
    requirement: 'The particulars of the declarations required to be specified under this rule on a package shall either be in Hindi in Devanagari script or in English (other languages permitted in addition).',
    statutoryExplanation: 'Protects consumer comprehension across India by ensuring at least English or Hindi Devanagari is used.',
    validationType: 'text_format',
    severity: 'MAJOR',
    automationStatus: 'AUTOMATED',
    actSectionPenalty: 'Section 36(1) of Legal Metrology Act, 2009',
    isActive: true,
  },
  {
    id: 'rule-lmr-26',
    ruleCode: 'LMR-26',
    ruleReference: 'Rule 26',
    title: 'Statutory Exemptions from Package Rules',
    category: 'Exemptions',
    requirement: 'Exempts: (a) Net weight/measure <=10g or <=10ml, (b) Fast food packed by restaurants/hotels, (c) Scheduled formulations under Drugs Price Control Order (DPCO), (d) Agricultural farm produce in packages above 50 kg.',
    statutoryExplanation: 'If declared net quantity is <=10g or <=10ml, certain declarations are not legally mandated.',
    validationType: 'conditional_presence',
    severity: 'ADVISORY',
    automationStatus: 'AUTOMATED',
    actSectionPenalty: 'N/A (Statutory Exemption Provision)',
    isActive: true,
  },
];

export const getAllRules = (category = null) => {
  if (category && category !== 'ALL') {
    return statutoryRules.filter((r) => r.category === category);
  }
  return statutoryRules;
};

export const getRuleById = (idOrCode) => {
  return (
    statutoryRules.find((r) => r.id === idOrCode || r.ruleCode.toLowerCase() === idOrCode.toLowerCase()) ||
    null
  );
};
